export const messagePopupStrings = {
    USER_UPDATED: 'User Record Updated.',
    USER_CREATED: 'User Record Created.',
    WIKIPEDIA_CREATED: 'Glossary Record Created',
    WIKIPEDIA_UPDATED: 'Glossary Record Updated',
    EXAMINATION_UPDATED: 'Examination Record Updated',
    EXAMINATION_CREATED: 'Examination Record Created',
    HISTORY_UPDATED: 'History Record Updated',
    HISTORY_CREATED: 'History Record Created',
    INVESTIGATION_UPDATED: 'Investigation Record Updated',
    INVESTIGATION_CREATED: 'Investigation Record Created',
    CASE_UPDATED: 'Case Record Updated',
    CASE_CREATED: 'Case Record Created',
    RESULT_CREATED: 'Result Record Created',
    RESULT_UPDATED: 'Result Record Updated',
};
