export const messagePopupStrings = {
    USER_CREATED: 'Admin Record Created.',
    USER_UPDATED: 'Admin Record Updated.',
    QUESTION_CREATED: 'Question Record Created',
    QUESTION_UPDATED: 'Question Record Updated',
    DECLARATION_CREATED: 'Report Record Created',
    DECLARATION_UPDATED: 'Report Record Updated',
    MEETING_CREATED: 'Meeting Record Created',
    MEETING_UPDATED: 'Meeting Record Updated',
    PATIENT_CREATED: 'User Record Created',
    PATIENT_UPDATED: 'User Record Updated',
    CONSULTANT_CREATED: 'Consultant Record Created',
    CONSULTANT_UPDATED: 'Consultant Record Updated',
    FEED_CREATED: 'Health Feed Record Created',
    FEED_UPDATED: 'Health Feed Record Updated',
    GAME_CREATED: 'Game Record Created',
    GAME_UPDATED: 'Game Record Updated',
    MEDITATION_CREATED: 'Meditation Record Created',
    MEDITATION_UPDATED: 'Meditation Record Updated',
};
